extends: relaxed

rules:
  line-length:
    max: 120
  new-line-at-end-of-file: enable
  empty-lines: disable
  document-start: disable
  comments: disable
  comments-indentation: disable
  indentation: disable
  trailing-spaces: enable
